import os

app_title = input("App Title: ")


def setup():
    os.chdir("/")
    os.system("echo [INFO] Creating project structure...")
    os.system("echo [INFO] Removing unnecessary folders...")
    os.system("echo [INFO] Removed unnecessary folders.")
    os.system("echo [INFO] Creating assets folder...")
    os.mkdir("assets")
    os.chdir("assets")
    os.mkdir("png")
    os.mkdir("svg")
    os.mkdir("translations")
    os.system("touch it.json")
    it_dot_json = open("it.json", "w")
    it_dot_json.write("{}")
    it_dot_json.close()
    os.mkdir("lotties")
    os.system("echo [INFO] Created assets folder.")
    os.chdir("../lib")
    os.system("echo [INFO] Creating lib folder...")
    os.mkdir("data")
    os.chdir("data")
    os.mkdir("models")
    os.mkdir("data_sources")
    os.mkdir("repositories")
    os.system("echo [INFO] Created data folder.")
    os.chdir("../lib")
    os.mkdir("domain")
    os.chdir("domain")
    os.mkdir("entities")
    os.mkdir("repositories")
    os.mkdir("usecases")
    os.system("echo [INFO] Created domain folder.")
    os.chdir("../lib")
    os.mkdir("presentation")
    os.chdir("presentation")
    os.mkdir("cubits")
    os.mkdir("screens")
    os.mkdir("widgets")
    os.system("echo [INFO] Created presentation folder.")
    os.chdir("../lib")
    os.mkdir("utils")


def main_dot_dart():
    main_dot_dart_file = open("main.dart", "w")
    main_dot_dart_file.write("import 'package:flutter/material.dart';\n")
    main_dot_dart_file.write("import 'package:flutter_bloc/flutter_bloc.dart';\n")
    main_dot_dart_file.write("import 'package:easy_localization/easy_localization.dart';\n\n")
    main_dot_dart_file.write("Future<void> main() async {\n")
    main_dot_dart_file.write("  WidgetsFlutterBinding.ensureInitialized();\n")
    main_dot_dart_file.write("  await EasyLocalization.ensureInitialized();\n")
    main_dot_dart_file.write("  await sharedPrefs.init();\n")
    main_dot_dart_file.write("  runApp(\n")
    main_dot_dart_file.write("    EasyLocalization(\n")
    main_dot_dart_file.write("      supportedLocales: const [\n")
    main_dot_dart_file.write("        Locale('it', 'IT'),\n")
    main_dot_dart_file.write("      ],\n")
    main_dot_dart_file.write("      path: 'assets/translations',\n")
    main_dot_dart_file.write("      fallbackLocale: const Locale('it', 'IT'),\n")
    main_dot_dart_file.write("      child: const MyApp(),\n")
    main_dot_dart_file.write("    ),\n")
    main_dot_dart_file.write("  );\n")
    main_dot_dart_file.write("}\n\n")
    main_dot_dart_file.write("class MyApp extends StatelessWidget {\n")
    main_dot_dart_file.write("  const MyApp({super.key});\n\n")
    main_dot_dart_file.write("  @override\n")
    main_dot_dart_file.write("  Widget build(BuildContext context) =>\n")
    main_dot_dart_file.write("      MaterialApp(\n")
    main_dot_dart_file.write("        debugShowCheckedModeBanner: false,\n")
    main_dot_dart_file.write("        localizationsDelegates: context.localizationDelegates,\n")
    main_dot_dart_file.write("        supportedLocales: context.supportedLocales,\n")
    main_dot_dart_file.write("        locale: context.locale,\n")
    main_dot_dart_file.write("        title: '$app_title',\n")
    main_dot_dart_file.write("        theme: ThemeData(useMaterial3: true),\n")
    main_dot_dart_file.write("        home: const SplashScreen(),\n")
    main_dot_dart_file.write("      );\n")
    main_dot_dart_file.write("}\n\n")
    main_dot_dart_file.close()


def pubspec_yaml():
    os.chdir("../")
    pubspec_file = open("pubspec.yaml", "w")
    pubspec_file.write("name: $app_title\n")
    pubspec_file.write("description: A new Flutter project.\n")
    pubspec_file.write("publish_to: 'none'\n")
    pubspec_file.write("version: 1.0.0+1\n\n")
    pubspec_file.write("environment:\n")
    pubspec_file.write("  sdk: '>=3.0.0'\n")
    pubspec_file.write("dependencies:\n")
    pubspec_file.write("  flutter:\n")
    pubspec_file.write("    sdk: flutter\n\n")
    os.system("flutter pub add easy_localization shared_preferences rxdart http equatable flutter_bloc")
    pubspec_file.write("dev_dependencies\n")
    pubspec_file.write("  flutter_test:\n")
    pubspec_file.write("    sdk: flutter\n\n")
    pubspec_file.write("flutter:\n")
    pubspec_file.write("  uses-material-design: true\n")
    pubspec_file.write("  assets:\n")
    pubspec_file.write("    - assets/\n")
    pubspec_file.write("    - assets/png/\n")
    pubspec_file.write("    - assets/svg/\n")
    pubspec_file.write("    - assets/translations/\n")
    pubspec_file.write("    - assets/lotties/\n")
    pubspec_file.close()


def main():
    setup()
    main_dot_dart()
    pubspec_yaml()


if __name__ == "__main__":
    main()
