name: Deploy Website

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          mkdir -p deploy
          cp -r website/build/web/. deploy/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
